### member测试端口
GET http://localhost:8010/member/hello
Accept: application/json

### gateway转发member测试端口
GET http://localhost:8000/member/hello
Accept: application/json

### 测试count方法
GET http://localhost:8000/member/count

### 注册接口
POST http://localhost:8000/member/register
Content-Type: application/x-www-form-urlencoded

mobile=99&

###
